# Generated by Django 3.1.7 on 2021-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('F', 'Свободен'), ('B', 'Занят')], help_text='Choice status', max_length=300, null=True, verbose_name='Status'),
        ),
    ]
